// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAprsmOtWPnQwODBnNuNFwUg5PNXwH2mTs',
    appId: '1:19464860322:android:08ff1600d87fcc4c2e5dfb',
    messagingSenderId: '19464860322',
    projectId: 'gerayo-amahoro-speed',
    databaseURL: 'https://gerayo-amahoro-speed-default-rtdb.firebaseio.com',
    storageBucket: 'gerayo-amahoro-speed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAeP6BmLDDckcJKnKBQgnmD0NxP4TS0gdI',
    appId: '1:19464860322:ios:23dc50c7ffa26b452e5dfb',
    messagingSenderId: '19464860322',
    projectId: 'gerayo-amahoro-speed',
    databaseURL: 'https://gerayo-amahoro-speed-default-rtdb.firebaseio.com',
    storageBucket: 'gerayo-amahoro-speed.firebasestorage.app',
    iosBundleId: 'com.speed.gerayoamahoro',
  );

}